import { createElement } from '@lwc/engine-dom';
import Lds_programatically_impretive_createRecord from 'c/lds_programatically_impretive_createRecord';

describe('c-lds-programatically-impretive-create-record', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lds-programatically-impretive-create-record', {
            is: Lds_programatically_impretive_createRecord
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});