import { createElement } from '@lwc/engine-dom';
import VlcPlayer_dependent_on_eventDeclarativelyLWC from 'c/vlcPlayer_dependent_on_eventDeclarativelyLWC';

describe('c-vlc-player-dependent-on-event-declaratively-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-vlc-player-dependent-on-event-declaratively-lwc', {
            is: VlcPlayer_dependent_on_eventDeclarativelyLWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});